import math
from py2_team_3_turbine_power_24 import turbine_power
from py2_team_3_heater_24 import heater



def main():
    v = float(input("Enter the velocity in m/s: "))
    t = float(input("Enter the time in hours: "))
    P = turbine_power(v)
    h = heater(t, P)

    print(f"The power generated by the turbine is {P:.1f} W")
    print(f"The amount of heat output by the heater is {h:.1f} J")

if __name__ == "__main__":
    main()